config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  resources :posts do
    collection do
      get 'search'
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'users/:id/message', to: 'users#message', as: :user_message

  root 'tops#index'
  
  post 'guest_admin_login', to: 'admin_guest_sessions#create'
  
  post 'guest_login', to: 'guest_sessions#create'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  
  enum priority: { 高: 0, 中: 1, 低: 2 }
  enum category: { 生活: 0, 仕事: 1, 健康: 2 }

  scope :sorted_by_priority, -> { order(priority: :asc) }
  scope :search, ->(query) { ransack(content_cont: query, public_eq: true).result } 

  def self.ransackable_attributes(auth_object = nil)
    [ "content" ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_q, only: [:index, :search]
  before_action :authenticate_user!, only: [:index]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.order(created_at: :desc)
    if params[:sort_priority] == 'true'
      @posts = @posts.reorder(priority: 'ASC')
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.public = params[:post][:public] != "true"
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @results = Post.where(public: true).where.not(user_id: current_user.id).ransack(params[:q]).result
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :priority, :category, :public)
    end

    def set_q
      @q = Post.ransack(params[:q])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: 'needs-validation', data: { 'was-validated': 'true' }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" style="margin-left: 20px;">
    <%= form.label :category, 'カテゴリー', class: 'form-label' %>
    <%= form.select :category, ['生活', '仕事', '健康'], { include_blank: 'カテゴリーを選択してください' }, class: 'form-select', required: true %>
  </div>

  <div class="mb-3" style="margin-left: 20px;">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', required: true, style: 'width: 300px;' %>
  </div>

  <div class="mb-3" style="margin-left: 20px;">
    <%= form.label :content, 'コンテンツ', class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control', required: true, style: 'width: 600px;' %>
  </div>

  <div class="mb-3" style="margin-left: 20px;">
    <%= form.label :priority, '優先度', class: 'form-label' %>
    <%= form.select :priority, [['高', '高'], ['中', '中'], ['低', '低']], { include_blank: '優先順位を選択してください' }, class: 'form-select', required: true %>
  </div>

  <div class="mb-3 form-check" style="margin-left: 20px;">
    <%= form.label :public, class: 'form-check-label' do %>
      <%= form.check_box :public, class: 'form-check-input', checked: true %>
      公開
    <% end %>
  </div>

  <div class="mb-3" style="margin-left: 20px;">
    <%= form.submit '作成', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿内容編集</h1>

<%= render 'form', post: @post %>

<%= link_to '詳細', post_path, class: 'btn btn-info ml-2' %>
<%= link_to '一覧画面', posts_path, class: 'btn btn-secondary ml-2' %>

app/views/posts/index.html.erb
<% if current_user.try(:admin?) %>
  <div class="container">
    <h1>管理者専用</h1>
  </div>
<% else %>
  <div class="container">
    <h1>一般</h1>
  </div>
<% end %>

<div class="container mt-4">
  <%= link_to '新規投稿', new_post_path, class: 'btn btn-info btn-sm' %>
  <span class="ml-2">
    <%= link_to "優先順位に並び替え", posts_path(sort_priority: "true"), class: 'btn btn-info  btn-sm' %>
    <%= link_to "メッセージ一覧", users_path, class: "btn btn-info btn-sm" %></li>
  </span>
</div>

<div class="container mt-4">
  <% @posts.group_by(&:category).each do |category, posts| %>
    <h2> <%= category %> </h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>コンテンツ</th>
          <th>優先度</th>
          <th>公開</th>
        </tr>
      </thead>
      <tbody>
        <% posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><%= post.priority %></td>
            <td><%= post.public %></td>
            <td><%= link_to '詳細', post, class: 'btn btn-success btn-sm' %></td>
            <td><%= link_to '編集', edit_post_path(post), class: 'btn btn-success btn-sm' %></td>
            <td>
              <%= link_to '消去', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<div class="container">
  <h1>コンテンツ検索</h1>
  <%= search_form_for @q, url: search_posts_path, html: { class: 'form-inline' } do |f| %>
    <div class="form-group">
      <%= f.label :content_cont, '調べたいキーワードを入力してください。' %>
      <%= f.search_field :content_cont, class: 'form-control' %>
    </div>
    <%= f.submit '検索', class: 'btn btn-primary ml-2' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', post: @post %>

<%= link_to '一覧画面', posts_path, class: 'btn btn-secondary ml-2' %>

app/views/posts/search.html.erb
<div class="container">
  <h1 class="mt-4">検索結果 ※お話したいユーザーを押してください</h1>
  <div class="table-responsive">
    <table class="table table-striped mt-4">
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>投稿者</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @results.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td>
              <%= link_to post.user.name, conversations_path(sender_id: current_user.id, recipient_id: post.user.id), method: :post, class: 'btn btn-link' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to '一覧場面', posts_path, class: 'btn btn-secondary mt-4' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Title:</h5>
      <p class="card-text"><%= @post.title %></p>
    </div>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Content:</h5>
      <p class="card-text"><%= @post.content %></p>
    </div>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Priority:</h5>
      <p class="card-text"><%= @post.priority %></p>
    </div>
  </div>

  <div class="mt-4">
    <%= link_to '編集', edit_post_path(@post), class: 'btn btn-warning' %>
    <%= link_to '一覧画面', posts_path, class: 'btn btn-secondary ml-2' %>
  </div>
</div>