config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  resources :posts do
    collection do
      get 'search'
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'users/:id/message', to: 'users#message', as: :user_message

  root 'tops#index'
  
  post 'guest_admin_login', to: 'admin_guest_sessions#create'
  
  post 'guest_login', to: 'guest_sessions#create'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # 会話はUserの概念をsenderとrecipientに分けた形でアソシエーションする。
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  # 一つの会話はメッセージをたくさん含む一対多。
  has_many :messages, dependent: :destroy

  # [:sender_id, :recipient_id]が同じ組み合わせで保存されないようにするためのバリデーションを設定。
  validates_uniqueness_of :sender_id, scope: :recipient_id

  # 下記で解説
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  # 下記で解説
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/notification.rb
# app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  scope :unread, -> { where(read: false) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  
  enum priority: { 高: 0, 中: 1, 低: 2 }
  enum category: { 生活: 0, 仕事: 1, 健康: 2 }

  scope :sorted_by_priority, -> { order(priority: :asc) }
  scope :search, ->(query) { ransack(content_cont: query, public_eq: true).result } 

  def self.ransackable_attributes(auth_object = nil)
    [ "content" ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

  validates :name, presence: true

  has_many :sent_conversations, foreign_key: :sender_id, class_name: 'Conversation'
  has_many :received_conversations, foreign_key: :recipient_id, class_name: 'Conversation'

  def conversations
    Conversation.where("sender_id = ? OR recipient_id = ?", id, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(user)
    posts_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @conversation = Conversation.find(params[:conversation_id])
    unless @conversation.sender == current_user || @conversation.recipient == current_user
      redirect_to conversations_path
    end

    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = Message.where(id: @messages[-10..-1].pluck(:id))
    end
  
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
  
    if @messages.last
      @messages.where.not(user_id: current_user.id).update_all(read: true)
    end
  
    @messages = @messages.order(:created_at)
    @message = @conversation.messages.build

  end

  def create
    @message = @conversation.messages.build(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    else
      render 'index'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController
  def index
    @notifications = current_user.notifications.order(created_at: :desc)
  end

  def mark_as_read
    notification = current_user.notifications.find(params[:id])
    notification.update(read: true)
    redirect_to notifications_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_q, only: [:index, :search]
  before_action :authenticate_user!, only: [:index]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.order(created_at: :desc)
    if params[:sort_priority] == 'true'
      @posts = @posts.reorder(priority: 'ASC')
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.public = params[:post][:public] != "true"
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @results = Post.where(public: true).where.not(user_id: current_user.id).ransack(params[:q]).result
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :priority, :category, :public)
    end

    def set_q
      @q = Post.ransack(params[:q])
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meyasubako</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag('favicon.ico') %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
    <div class="container">
      <%= link_to posts_path, class: "navbar-brand" do %>
        <%= image_tag 'logo.png', alt: 'Meyasubako ロゴ', width: 80, height: 80 %>
      <% end %>
      <style>
        .navbar-toggler-icon.custom-icon {
          background-color: white; 
        }
      </style>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon custom-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <style>
          .navbar-nav .nav-item .nav-link {
            color: white !important; 
          }
        </style>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item"><div class="nav-link"><%= current_user.name %>の部屋</div></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "アカウント登録", new_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
          <% end %>
        </ul>
        <%= link_to root_path do %>
          <div style="display: flex; align-items: center;">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
              <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
            </svg>
            <span style="margin-left: 8px;">トップページ</span>
          </div>
        <% end %>
        <% if notice %>
          <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <% if current_user && current_user.admin? %>
            <li class="nav-item"><%= link_to "管理者ページ", rails_admin_path, class: "nav-link", data: { turbolinks: "false" } %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <%= yield %>
  <style>
    .content {
      margin-bottom: 100px; 
    }
  </style>
  <div class="content"></div>
  <footer class="footer fixed-bottom bg-secondary">
    <div class="container text-center">
      <span class="text-white">Meyasubako &copy; <%= Time.now.year %></span>
    </div>  
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>